drop database IF EXISTS eqi;
create database eqi;
GRANT ALL ON eqi.* TO invitado@localhost;

use eqi;
DROP TABLE IF EXISTS ALUMNOS;
CREATE TABLE ALUMNOS (
                ALUMID   INT NOT NULL,
                ALUMNOMS CHAR(30) NOT NULL,
                ALUMAPEP CHAR(30) NOT NULL,
                ALUMBOLE INT NOT NULL,
                ALUMCARR CHAR(30) NOT NULL,    
                PRIMARY KEY(ALUMID));	

INSERT INTO ALUMNOS VALUES(1,'RICARDO','BARRERA',2015600023, 'INFORMATICA');
INSERT INTO ALUMNOS VALUES(2,'UVALDO','ESCOBEDO',2015600596, 'INFORMATICA');
INSERT INTO ALUMNOS VALUES(3,'ROBERTO','CRUZ',2020600265, 'ADMINISTRACION');
INSERT INTO ALUMNOS VALUES(4,'IVAN','JASSO',2015600158, 'INDUSTRAIL');
INSERT INTO ALUMNOS VALUES(5,'RAUL','GOMEZ',2015600896, 'TRANSPORTE');
INSERT INTO ALUMNOS VALUES(6,'GUADALUPE','MARQUEZ',2015600193, 'INFORMATICA');
INSERT INTO ALUMNOS VALUES(7,'DANIEL','GARCIA',2015600456, 'ADMINISTRACION');
INSERT INTO ALUMNOS VALUES(8,'GISELA','ROA',2015600281, 'ADMINISTRACION');
INSERT INTO ALUMNOS VALUES(9,'EMMANUEL','MARTINEZ',2015600819, 'ADMINISTRACION');




